apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
     app: web
spec:
  containers:
  - name: web
    image: localhost:32000/web
    command: ["/bin/bash", "-c","--", "/start.sh"]
    # The pod template ends here
