apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql2-volume
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath 
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mylogs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql2-claim
spec:
  storageClassName: microk8s-hostpath 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql2
  labels:
    app: sql2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql2
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sql2
        tier: frontend
    spec:
      containers:
      - name: sql2
        imagePullPolicy: Always
        image: localhost:32000/sql
        command:  ["/bin/bash", "-c","--", "/app/sql"]
        volumeMounts:
        - mountPath: "/mylogs"
          name: mypd
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: sql2-claim
      restartPolicy: Always

